name: simpleapp
version: 1.2.3
description: >
  Have you been turned into a newt?  Would you like to be?
  This package can help: it has all of the
  newt-transmogrification functionality you have been looking
  for.
author: Jermaine Oppong
homepage: http://www.graphicbeacon.com
dependencies:
  http_server: ">=0.9.5+1 <0.10.0"
  route: any
  path: ">=1.3.3 <2.0.0"
  uuid: ">=0.5.0 <0.6.0"